(defpackage :cc
  (:use :cl :common-lisp :cffi)
  (:export :main))

(defpackage :cc-event
  (:use :cl :common-lisp :cffi)
  (:export
   :event-enable-debug-mode
   :event-debug-unassign
   :event-base-new
   :event-reinit
   :event-base-dispatch
   :event-base-get-method
   :event-get-supported-methods
   :event-gettime-monotonic
   :*EVENT-BASE-COUNT-ACTIVE*
   :*EVENT-BASE-COUNT-VIRTUAL*
   :*EVENT-BASE-COUNT-ADDED*
   :event-base-get-num-events
   :event-base-get-max-events
   :event-config-new
   :event-config-free
   :event-config-avoid-method
   :*EV-FEATURE-ET*
   :*EV-FEATURE-O1*
   :*EV-FEATURE-FDS*
   :*EV-FEATURE-CLOSE*
   :*EVENT-BASE-FLAG-NOLOCK*
   :*EVENT-BASE-FLAG-IGNORE-ENV*
   :*EVENT-BASE-FLAG-STARTUP-IOCP*
   :*EVENT-BASE-FLAG-NO-CACHE-TIME*
   :*EVENT-BASE-FLAG-EPOLL-USE-CHANGELIST*
   :*EVENT-BASE-FLAG-PRECISE-TIMER*
   :event-base-get-features
   :event-config-require-features
   :event-config-set-flag
   :event-config-set-num-cpus-hint
   :event-config-set-max-dispatch-interval
   :event-base-new-with-config
   :event-base-free
   :event-base-free-nofinalize
   :*EVENT-LOG-DEBUG*
   :*EVENT-LOG_MSG*
   :*EVENT-LOG-WARN*
   :*EVENT-LOG-ERR*
   :event-set-log-callback
   :event-set-fatal-callback
   :*EVENT-DBG-ALL*
   :*EVENT-DBG-NONE*
   :event-enable-debug-logging
   :event-base-set
   :*EVLOOP-ONCE*
   :*EVLOOP-NONBLOCK*
   :*EVLOOP-NO-EXIT-ON-EMPTY*
   :event-base-loop
   :event-base-loopexit
   :event-base-loopbreak
   :event-base-loopcontinue
   :event-base-got-exit
   :event-base-got-break
   :*EV-TIMEOUT*
   :*EV-READ*
   :*EV-WRITE*
   :*EV-SIGNAL*
   :*EV-PERSIST*
   :*EV-ET*
   :*EV-FINALIZE*
   :*EV-CLOSED*
   :event-self-cbarg
   :event-new
   :event-assign
   :event-free
   :event-finalize
   :event-free-finalize
   :event-base-once
   :event-add
   :event-remove-timer
   :event-del
   :event-del-noblock
   :event-del-block
   :event-active
   :event-pending
   :event-base-get-running-event
   :event-initialized
   :event-get-fd
   :event-get-base
   :event-get-events
   :event-get-callback
   :event-get-callback-arg
   :event-get-priority
   :event-get-assignment
   :event-get-struct-event_size
   :event-get-version
   :event-get-version-number
   :event-base-priority-init
   :event-base-get-npriorities
   :event-priority-set
   :event-base-init-common-timeout
   :event-set-mem-functions
   :event-base-dump-events
   :event-base-active-by-fd
   :event-base-active-by-signal
   :event-base-foreach-event
   :event-base-gettimeofday-cached
   :event-base-update-cache-time
   :libevent-global-shutdown   
   ))

